name: Dr. J
favicon: null
layout_spectrum: 0.47331697726622224
typography_spectrum: 0.9874233540613204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#3d2d21'
    - '#a7a29f'
    - '#c37d62'
    - '#f3b187'
  brandStrength: 0.25
  lightness: 0.23160593351349235
  saturation: 0.01696730451658368
  rhythmicContrast: 0.8378783445805311
purpose: []
